### ISSUE TITLE
Plural version of {{ .Name }} ?

### ISSUE THREAD

**Issue by Michsior14** [knq/xo#105]
Is there plural version of {{ .Name }} available? It would be perfect to use it when creating slices of model in template.

**Comment by kenshaw** [comment]
The func's that are made available to the templates are defined in `internal/funcs.go`, however there is no "plural" template func at the moment. For reference, `xo` uses package [`inflector`](https://github.com/gedex/inflector) to `Singularize` and `Pluralize` names. It would be fairly straight forward to make this available to templates by adding a wrapper to `inflector.Pluralize` in `funcs.go`. Unfortunately, this is kind of the limitation of working with Go's templates, and I do not expect that we will in the `xo` code base add this, as it is not used by the base templates. 

The best way to work around this is to branch the `xo` code and version it with your project. I realize this is frustrating/not ideal, but its partly a limitation of how the underlying technology works (ie, Go templates), which twists one's arm in what can be offered in the base `xo` tool.
