### ISSUE TITLE
Influence generated enum type names?

### ISSUE THREAD

**Issue by ottob** [knq/xo#11]
In the example you have this:
```go
const (
    // FictionBookType is the book_type for 'FICTION'.
    FictionBookType = BookType(1)

    // NonfictionBookType is the book_type for 'NONFICTION'.
    NonfictionBookType = BookType(2)
)
```
But I prefer the generated names to be:
```go
const (
    // BookTypeFiction is the book_type for 'FICTION'.
    BookTypeFiction = BookType(1)

    // BookTypeNonfiction is the book_type for 'NONFICTION'.
    BookTypeNonfiction = BookType(2)
)
```
I think this will make them easier to find through an IDE. And more in line with go std lib like https://golang.org/src/net/http/status.go

Is this possible?

**Comment by kenshaw** [comment]
Sorry for the late reply, was busy over the last day.

Yes, this is fairly easy to do by customizing the templates that you are using, and then passing the template directory via the xo command line. You can do that via the following:

```sh
# copy templates to a working directory
mkdir -p $GOPATH/src/mytemplates
cp $GOPATH/src/github.com/knq/xo/templates/postgres.*.tpl $GOPATH/src/
cd $GOPATH/src/mytemplates

# edit the templates ...
vi postgres.enum.go.tpl

# generate models with xo
xo --template-path $GOPATH/src/mytemplates pgsql://user:pass@host/dbname -s myschema
```

The template you need to modify is the 'enum' template. It is prefixed with the name of the database driver:

```sh
ken@ken-desktop:~$ cd $GOPATH/src/github.com/knq/xo/templates
ken@ken-desktop:~/src/go/src/github.com/knq/xo/templates$ ls
mssql.foreignkey.go.tpl  mysql.foreignkey.go.tpl  oracle.foreignkey.go.tpl  postgres.foreignkey.go.tpl  sqlite3.foreignkey.go.tpl  xo_db.go.tpl
mssql.index.go.tpl       mysql.index.go.tpl       oracle.index.go.tpl       postgres.index.go.tpl       sqlite3.index.go.tpl       xo_package.go.tpl
mssql.query.go.tpl       mysql.proc.go.tpl        oracle.query.go.tpl       postgres.proc.go.tpl        sqlite3.query.go.tpl
mssql.querytype.go.tpl   mysql.query.go.tpl       oracle.querytype.go.tpl   postgres.query.go.tpl       sqlite3.querytype.go.tpl
mssql.type.go.tpl        mysql.querytype.go.tpl   oracle.type.go.tpl        postgres.querytype.go.tpl   sqlite3.type.go.tpl
mysql.enum.go.tpl        mysql.type.go.tpl        postgres.enum.go.tpl      postgres.type.go.tpl        tpls.go
ken@ken-desktop:~/src/go/src/github.com/knq/xo/templates$
```

**Comment by kenshaw** [comment]
I just looked at the enum file to refresh my memory on what fields need to be changed. If you need a quick shortcut to do what you are looking to accomplish, basically you need to change all instances of `{{ .Name }}{{ $type }}` to `{{ $type }}{{ .Name }}` in that file. I believe that should be all that's necessary. There are 4 instances in that file.

A perl one liner to change the name:
```sh
perl -pi -e 's/{{ \.Name }}{{ \$type }}/{{ \$type }}{{ \.Name }}/g' postgres.enum.go.tpl
```

BTW -- I don't think the proper noun followed by the instance name is idiomatic Go. I've seen it different ways in what I would consider to be idiomatic Go (standard library, and others).

**Comment by kenshaw** [comment]
Part of the original decision behind this is also to reflect other custom code generators that are being used on projects that we are working on. That said, after thinking about this, I think you are likely right that it should be the other way around for naming. As such, I'll make a point in the next few days to add an option to do it the way this is currently done, and to make the default as what you are suggesting to better match with http.Status* and package.Err style naming conventions.

**Comment by kenshaw** [comment]
Quick note that yesterday I pushed a change to make this the default, with a command line switch to toggle the previous name generation.
