### ISSUE TITLE
error: open file.xo.go: too many open files

### ISSUE THREAD

**Issue by phamdt** [knq/xo#124]
i ran xo against a mysql db with over 300 tables and received the following error:

`error: open {path to the last generated file}.xo.go: too many open files`

it did generate 251 files for the respective tables though.

**Comment by kenshaw** [comment]
This is likely a `ulimit` problem. Try increasing the number of open files allowed:

```sh
ulimit -n 2048
```

**Comment by phamdt** [comment]
Worked!
