### ISSUE TITLE
How to save uint64 into DB

### ISSUE THREAD

**Issue by suntong** [knq/xo#134]
This is my custom query:

```sql
SELECT
  date, price
FROM sales
WHERE type_id= %%type_id int%%
  AND key = %%key uint64%%
```

when it is converted to custom-query function, and I pass a `uint64` to such function, I'll get error:

    sql: converting Exec argument $2 type: uint64 values with high bit set are not supported

The sql driver is mattn/go-sqlite3 BTW,

So how to save uint64 into DB? Thx.

**Comment by suntong** [comment]
https://groups.google.com/forum/?hl=en#!topic/golang-nuts/QmvMMPcoVcs

**Comment by natefinch** [comment]
Thanks for linking to the solution!

**Comment by suntong** [comment]
@natefinch, Thank you. 

For proof, see https://github.com/suntong/lang/blob/master/lang/Go/src/ds/builtin.go
