### ISSUE TITLE
Naming collision with multiple foreign keys referencing one table

### ISSUE THREAD

**Issue by nochso** [knq/xo#14]
Tables with multiple foreign keys that point to the same foreign table result in naming collisions.

A simplified schema of what I'm working with:
```sql
CREATE TABLE "address" (
  "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  "name" text NOT NULL
);
CREATE TABLE "mail" (
  "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  "sender_id" integer NOT NULL,
  "recipient_id" integer NOT NULL,
  FOREIGN KEY ("recipient_id") REFERENCES "address" ("id"),
  FOREIGN KEY ("sender_id") REFERENCES "address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX "idx_mail_recipient_id" ON "mail" ("recipient_id");
CREATE INDEX "idx_mail_sender_id" ON "mail" ("sender_id");
```
`mail.xo.go` ends up containing this:
```go
// Address returns the Address associated with the Mail's RecipientID (recipient_id).
//
// Generated from foreign key 'mail_recipient_id_fkey'.
func (m *Mail) Address(db XODB) (*Address, error) {
	return AddressByID(db, m.RecipientID)
}

// Address returns the Address associated with the Mail's SenderID (sender_id).
//
// Generated from foreign key 'mail_sender_id_fkey'.
func (m *Mail) Address(db XODB) (*Address, error) {
	return AddressByID(db, m.SenderID)
}
```

I'd like to suggest naming those functions differently. How about using the column name without `_id`? e.g. `Recipient()` and `Sender()`? or maybe even combine it with the table name: `RecipientAddress()` and `SenderAddress()`?

Unless of course I'm missing something. I could probably copy the templates and modify them for now, but I'd rather see this fixed :)

**Comment by kenshaw** [comment]
Yes, I see the issue. I'm working on a fix for this now. What will end up happening is that there will likely be 2 new command line options that toggle behavior for this, however I'm looking into seeing if there is a way to detect this automatically and force the behavior.

**Comment by kenshaw** [comment]
I've pushed a change that should fix this in the default case, and introduces a new command line option, `--fk-mode` that provides a number of different types of foreign key modes. The default, `smart` will look if there are other foreign keys with that same parent name and use the `field` foreign key mode, otherwise if there are no collisions, then the `parent` foreign key mode will be used.

A summary of the foreign key modes / behaviors:
```
smart  - default behavior; will use parent when no name collisions, and field when there are
parent - foreign key funcs on generated types as will be in the form of '<RefTable>'.
field  - foreign key funcs on generated types as will be in the form of '<RefTable>By<FieldName>'
key    - foreign key funcs on generated types as will be in the form of '<RefTable>By<KeyName>'
```

For example, if you have a simple `authors` and `books` relationship (as in the examples), then the following will be the result for the different modes:
```
parent - func (b *Book) Author()
field  - func (b *Book) AuthorByAuthorID()
key    - func (b *Book) AuthorByFk123() // (assuming the foreign key name is 'fk_123')
```

**Comment by kenshaw** [comment]
Let me know if that works for you. 

I am hesitant to do anything more complicated or to change the templates, as I think if there is more custom logic/behavior necessary, then one likely needs to use custom templates for their schema as it is not possible to accommodate all the different schema designs styles, and also still work across the supported database types, here.

**Comment by nochso** [comment]
Thank you very much! The change works fine for me.

Just one minor thing: the default argument for `--fk-mode` shows as a pointer to FkMode.
```
  --fk-mode FK-MODE, -k FK-MODE
                         sets mode for naming foreign key funcs in generated Go code [values: <smart|parent|field|key>] [default: smart] [default: 0xc82000e978]
```

**Comment by kenshaw** [comment]
I'm aware of the issue -- it's a problem with the package I'm using for command line argument parsing, which is why I manually put the other [default: smart] text there. 

Glad it works for you!
