### ISSUE TITLE
PostgreSQL functional indexes

### ISSUE THREAD

**Issue by wttw** [knq/xo#15]
The entry in [pg_index](http://www.postgresql.org/docs/current/static/catalog-pg-index.html) for a postgresql functional index has indkey=0, leading to NULL results from the PgIndexColumns query:

    error: sql: Scan error on column index 1: converting driver.Value type <nil> ("<nil>") to a int: invalid syntax

Adding `i.indkey <> '0' AND` to the where clause in both PgIndexColumns and PgTableIndexes seems to be the right fix.

(I'd do this as a pull request, but I don't have databases in place to test the go generate step).

**Comment by kenshaw** [comment]
Yeah -- I'm aware of this issue. The problem is I'm not really sure how to detect a functional index as opposed to a plain/columnar index. I'll do some research into pg_catalog and see if I can find something that would eliminate this issue.

With regards to a functional index, how would you expect the Go built model to generate? Suppose on the books example you have this index:
```sql
CREATE INDEX books_title_lower ON books (lower(title));
```
Would one expect the generated package to have a func like:
```go
func BooksByTitleLower(title string) ([]*Book, error) { /* ... */ }
```
If so, this is a special case for PostgreSQL, as I'm not aware of the other supported databases supporting functional indexes.

**Comment by kenshaw** [comment]
A cursory Google search would lead me to believe that every database except MySQL supports some kind of computed/functional expression indexes over one or more columns.

**Comment by wttw** [comment]
I'd be quite happy for the code generated by xo to not have any support for functional indexes, just ignoring them (and not erroring out when it sees a table with one). The change I suggested (checking for '0' in pg_index.indkey) does that, stopping xo from trying to do anything with them.

Something fancier that provided Go model access to queries using functional indexes would be a nice trick, but it'd be quite database-specific (and working out how to name them automatically in the Go model might be tricky).

I know Oracle has functional indexes too, at least.

**Comment by kenshaw** [comment]
Yeah -- I think that's the best stop-gap measure for now. I'm in the middle of creating a more powerful/general purpose tool that will share a common library with xo that might eventually lead to some kind of better / cross-platform support for this. Ideally, I'd want xo to be able to detect all indexes (regardless of computed column info on the index) and create appropriate Go func's as needed. That's really quite hard based on the simple/naive SQL implementation currently in xo.

**Comment by wttw** [comment]
Yeah, best thing for now.

pg_index.indkey, pg_index.inexprs and pg_index.indpred are the columns to identify the different index type in PostgreSQL, though pulling usable information about what's in the functional index might take some work.

**Comment by kenshaw** [comment]
I have pushed the quick fix as suggested. It works, but I have only tried with one single column. A lot more testing needs to go into this (for PostgreSQL and for the other databases as well), however I don't have the time today to do that.
