### ISSUE TITLE
Postgres UUID Types.

### ISSUE THREAD

**Issue by whitebook** [knq/xo#17]
Sorry to open another issue while we are still working on the first, but I wanted to mention something I noticed as well.

I generated the models without issue using "xo"

I noticed it created this "UUID" type.
But I don't see it imported???

Not sure if this is by design or my mistake.

Thanks.

package models

// GENERATED BY XO. DO NOT EDIT.

import (
        "database/sql"
        "errors"
)

// VUser represents a row from public.v_users.
type VUser struct {
        UserUUID    UUID           // user_uuid
        DomainUUID  UUID           // domain_uuid
        Username    sql.NullString // username
        Password    sql.NullString // password
        Salt        sql.NullString // salt
        ContactUUID UUID           // contact_uuid
        UserStatus  sql.NullString // user_status
        APIKey      UUID           // api_key
        UserEnabled sql.NullString // user_enabled
        AddUser     sql.NullString // add_user
        AddDate     sql.NullString // add_date

        // xo fields
        _exists, _deleted bool
}

**Comment by kenshaw** [comment]
UUID is a custom PostgreSQL type. You need to supply a package that supports that type via either the `--custom-type-package` or `-C`. That type needs to be Marshal'able by the PostgreSQL Go driver to the database. That's fairly easy to do -- you only need to supply compatible `Scanner` and `Valuer` interfaces for that UUID type. You can see an example of that in the generated xo_db.xo.go file, which provides a StringSlice type for working with string arrays in PostgreSQL.

This is an artifact of working with static typing in both PostgreSQL and Go. If you don't want to create a type that supports the `Scanner` or `Valuer` interface, then you might want to consider storing your UUIDs as strings (text/varchar/etc) in the database instead, and creating a UUID index over that field, as well as a CHECK() constraint.

**Comment by kenshaw** [comment]
Oh -- one quick note -- if you want to just quickly generate your schema and later come back to write the Go types for your custom database types, then you can use `-C pgtypes`, which contains all the PostgreSQL custom defined types and is in the `xo/examples/pgtypes` directory.

**Comment by whitebook** [comment]
Got it! Thx.

**Comment by odewahn** [comment]
Hi!  I'm having the same issue, @whitebook.  Do you have an example of how you got this to work?

ps -- thanks for this great package, @kenshaw

**Comment by kenshaw** [comment]
PostgreSQL's UUID isn't supported in full by the `lib/pq` driver -- it just sends the read/writes the UUID as a string. All you need to do is define a `UUID` type supporting the `Scanner` and `Valuer` interfaces. You can put this in the same output directory as xo writes to, or you can use some other package that has predefined types and the name of that package via the `--custom-type-package` command line option. 

I'm fairly certain all you need to do is define a type alias in Go like this:
```go
// go/src/github.com/knq/mycustomtypes/mycustomtypes.go
package mycustomtypes

type UUID string
```

You would just need to then do this:
```sh
xo --custom-type-package mycustomtypes -o models pgsql://user:pass@host/dbname
```

**Comment by odewahn** [comment]
Thanks, @kenshaw.  I'll give that a try.

**Comment by odewahn** [comment]
Thanks again for your help, @kenshaw.  Just to close the loop in case others have this question, this is what I did:

First, I created a file called "uuid.go" in the same directory as the generated xo models.  It's content is:

```
package models

import (
	"database/sql/driver"
	"errors"
)

// UUID defines the postgres UUID custom type
type UUID struct {
	Val string
}

// Scan satisfies the sql.Scanner interface for UUID.
func (ss *UUID) Scan(src interface{}) error {

	buf, ok := src.([]byte)
	if !ok {
		return errors.New("invalid UUID")
	}

	*ss = UUID{string(buf)}
	return nil

}

// Value satisfies the driver.Valuer interface for UUID.
func (ss UUID) Value() (driver.Value, error) {
	return ss.Val, nil
}
```

I could then call it using this:

```
	project, err := models.ProjectByID(db, models.UUID{"d0bf9d77-cd81-4ad6-ace0-f0be928574a2"})
```

Might not be exactly right, but it seems to be working for me so far.
