### ISSUE TITLE
sql scan err: []uint8 into *time.Time

### ISSUE THREAD

**Issue by sethgrid** [knq/xo#19]
Hi. I was testing out your package and either did something wrong or found a bug:
```
$ go run main.go
2016/05/28 12:12:26 main.go:31: sql: Scan error on column index 1: unsupported Scan, storing driver.Value type []uint8 into type *time.Time
exit status 1
```

To reproduce, use the following mysql schema:
```
CREATE TABLE `some_table` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `some_int` int(11) NOT NULL,
  `some_nullable_int` int(11) DEFAULT NULL,
  `some_string` varchar(100) NOT NULL,
  `some_nullable_string` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8;
```

Generate the schema: `xo mysql://root@localhost/allthethings -o models`

and run the following main (note, obviously use your own model dir):
```
package main

import (
	"database/sql"
	"log"

	_ "github.com/go-sql-driver/mysql"
	"< PATH TO MODEL>"
)

func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)

	db, err := sql.Open("mysql", "root@tcp(localhost:3306)/allthethings")
	if err != nil {
		log.Fatal(err)
	}
	err = db.Ping()
	if err != nil {
		log.Fatal(err)
	}

	st := models.SomeTable{SomeString: "foo"}
	err = st.Insert(db)
	if err != nil {
		log.Fatal(err)
	}

        // the following line errors
	results, err := models.SomeTablesBySomeString(db, "foo")
	if err != nil {
		log.Fatal(err)
	}

	for _, r := range results {
		log.Printf("Found id %d", r.ID)
	}
	log.Println("complete")
}
```

The error happens at `results, err := models.SomeTablesBySomeString(db, "foo")`.

**Comment by kenshaw** [comment]
Is there an index missing in the schema you provided? I had no trouble generating models from the provided schema, however the `SomeTablesBySomeString` method isn't there -- so I'm assuming you're creating an index on `some_string`?

For what it's worth, the error you have listed indicates column 1, which I believe is the `created` field. I modified the code accordingly, and had no problems with it. It could be an issue with the version of MySQL you are using. For what it's worth, I've been doing my testing against MariaDB 10.0.23-0ubuntu0.15.10.1. I'm fairly certain it should work just fine with any other MySQL compatible client. 

The `Scan` method delegates to the actual sql driver. If there is an issue there, I'm sure we can come up with a workaround if there's some kind of incompatibility with timestamp columns on whatever version of MySQL you're using.

**Comment by kenshaw** [comment]
I would like to fix this, but I cannot do so without the requested information -- namely the MySQL version you are using. I cannot reproduce this in my environment, and I am not able to test every MySQL/MariaDB/Percona/etc version that exists out there.

**Comment by kenshaw** [comment]
This is not an issue with xo -- I just realized that you must pass the mysql driver the `parseTime=true` parameter. Please see examples/mysql/booktest.go where the `sql.Open` call is.

**Comment by kenshaw** [comment]
Please note I just updated the examples to use [dburl](https://github.com/knq/dburl) to open the database connection. It works the same as `sql.Open`, except that it processes a URL instead of a driver and dsn string.

**Comment by sethgrid** [comment]
sorry for my unresponsiveness! Your solution is perfect, thanks for taking the time and figuring that out. Glad to see it was an error on my part and not something wrong with the library. Thanks!
