### ISSUE TITLE
Tests do not use transaction

### ISSUE THREAD

**Issue by tarqe39** [knq/xo#21]
Hi, it seems that test do not use created transactions.
You have:
`tx, err := db.Begin()`
and later on
`err = b0.Save(db)`
instead of
`err = b0.Save(tx)`

Also, there should be a defered rollback i suppose.

**Comment by kenshaw** [comment]
Yes, you're right. This likely happened due to rewriting the examples multiple times. Thanks for catching that. I'll fix this soon.

**Comment by tarqe39** [comment]
No problem. Glad I could help :)
