### ISSUE TITLE
Pointer to time.Time when column is not null

### ISSUE THREAD

**Issue by achiku** [knq/xo#23]
Hi, I have a question.

Why is this library using `*time.Time` for not null column? It seems like `pq.NullTime` is for nullable time column when transforming table to struct.

**Comment by kenshaw** [comment]
`*time.Time` is more consistent with the other SQL drivers for their time implementations. Ideally, there would be some kind of user supplied mapping to override this (or any other generated type), but I have not yet had time to implement that.

Also, it is possibly more 'idiomatic' to support the native Go types, as that has better compatibility with other libraries. Quite frankly, I really dislike the native type support that is available for SQL, but there is not much that can be done. That's likely just an issue that no SQL driver implementations (that I'm aware of) have been written by the Go authors, only the interfaces/pooling lib in the standard library.

**Comment by kenshaw** [comment]
I just noticed that there are inconsistencies with this. While I won't be changing to `pq.NullTime`, I will clean up the type conversion for time across the various drivers, which is part of the work that is also needed to better standardize the type parsing across all the loaders.

**Comment by achiku** [comment]
I see your point. I don't really have deep knowledge of Go SQL drivers, but it just seemed to be fine to set `time.Time` instead of `*time.Time` if a column is guaranteed to be non null.

If you feel ok, could you tell me any idea or rough destination of how to implement user supplied mapping  of types? I can look into the code and might be able to help implementing it :)
