### ISSUE TITLE
Tables with names beginning with "q" and indexes generate invalid code

### ISSUE THREAD

**Issue by wttw** [knq/xo#24]
`"q.Scan undefined (type Queue has no field or method Scan)"`

If the table name is such that shortname is "q" that clashes with the use of "q" to hold the result of db.Query in code generated from postgres.query.go.tpl.

(Changing "q" to "_q" in a local copy of the template used with --template-path works around it easily enough.)

**Comment by kenshaw** [comment]
Yeah, oops. Will fix.

**Comment by kenshaw** [comment]
An update: this is actually a fairly difficult thing to do, in many ways, as I'm not happy with just 'renaming' every variable used within scopes to have an underscore (or similar), as I want the generated code to look like it was written by a person. I have a solution that is roughly 50% complete, and I am hoping to get this pushed out soon.

**Comment by kenshaw** [comment]
BTW -- I apologize this fix took so long to come out. It required a lot of attention and I did not have much time to work on this over the last month. I tested this fairly thoroughly with a bunch of schemas, but it definitely needs to be more rigorous. I'd appreciate feedback on this, if you have it. Thanks!
