### ISSUE TITLE
Insert function assumes primary key is auto increment

### ISSUE THREAD

**Issue by bproctor** [knq/xo#28]
The code generated for the Insert() function assumes that that the primary key is auto increment and does not insert it and uses LastInsertId to set it.

**Comment by kenshaw** [comment]
Yes; I would suggest creating custom templates using the base templates then. I am working on a general solution for this, but it is not yet ready to be released, as it requires a lot of rejigging of the templates.

**Comment by yurisklar** [comment]
Is this issue going to be addressed any time soon? Or would you accept some help with the implementation?

**Comment by stevenh** [comment]
A related issue we have is it assumes a primary key is a single field which is not necessarily the case.

**Comment by kenshaw** [comment]
Yes, for reference I would appreciate any pull requests. We don't make any use of SQLite at my company, so I'm not likely to ever get around to fixing this. I'm more than willing to help with / give advice on / test any pull request.

**Comment by turnkey-commerce** [comment]
I think for SQLite we can do an additional query to determine if it's autoincrement, see this SO answer: http://stackoverflow.com/questions/20979239/how-to-tell-if-a-sqlite-column-is-autoincrement.  I'll take a look at implementing this as the problem was apparent on the SQLite DB I was testing,.

**Comment by turnkey-commerce** [comment]
Am working on this but found that for new databases, for example the Django example, the sqlite_sequence is not reliably populated.  Workin on  an alternate method to query for the SQL and check for the AUTOINCREMENT keyword for the table.

**Comment by turnkey-commerce** [comment]
Ken, this is resolved can you please close it?
