### ISSUE TITLE
MySQL driver selects int16 for MEDIUMINT type

### ISSUE THREAD

**Issue by bproctor** [knq/xo#29]
Should use int32 instead

**Comment by kenshaw** [comment]
Sorry. MySQL type parsing needs to be rewritten. It's the only one where I basically copied the parsing from the PostgreSQL implementation, and did not thoroughly go over the documentation as well as I should have. Oracle, MSSQL, and SQLite all got implemented from scratch.

**Comment by bproctor** [comment]
Thank you for your work on this project and sharing it. Previously I was writing code by hand that looked almost exactly like what xo generates so this project has been a huge time saver.
