### ISSUE TITLE
pg stored procedures returning trigger generate code with undefined type Trigger

### ISSUE THREAD

**Issue by yargevad** [knq/xo#34]
```pgsql
CREATE OR REPLACE FUNCTION public.fake_trigger(
) RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RETURN NEW;
END;
$$;
```

generates:

```go
// FakeTrigger calls the stored procedure 'public.fake_trigger() trigger' on db.
func FakeTrigger(db XODB) (Trigger, error) {
  var err error

  // sql query
  const sqlstr = `SELECT public.fake_trigger()`

  // run query
  var ret Trigger
  XOLog(sqlstr)
  err = db.QueryRow(sqlstr).Scan(&ret)
  if err != nil {
    return Trigger{}, err
  }

  return ret, nil
}
```

which fails to build with `models/sp_faketrigger.xo.go:7: undefined: Trigger`

**Comment by kenshaw** [comment]
Also an oversight. I don't believe this should be generated in any fashion for SQL at least.

**Comment by yargevad** [comment]
I agree, these functions aren't called directly. I'm working around this for now with

```bash
for fn in $(grep -l Trigger models/*.go) ; do
  rm "$fn"
done
```

Thanks!

**Comment by kenshaw** [comment]
For reference, you could also use the `--custom-type-package` with the `pgtypes` package found in the examples/pgcatalog. Alternatively, you could just create this go file:
```go
type Trigger struct {}
```
And put it with the same package name as your generated files. Anyways, I'll have a fix for this and the void type soon.
