### ISSUE TITLE
Check exist on index

### ISSUE THREAD

**Issue by suntong** [knq/xo#36]
Any plan to add checking `exist` on index in xo? 

Other than returning all rolls for an index (feature generated by xo), many times, people just want to checking the existence of the index key, and `count` maybe as well. 

Any plan to add generated code for it/them? Thx.

**Comment by kenshaw** [comment]
xo has the ability to accept a folder with custom templates with the `--template-path` command line option. The functionality you're requesting is not something that is general purpose, and thus would not be added to the built in templates. It would be very easy to add that logic to a set of custom templates.
