### ISSUE TITLE
Multi-DBs in the same project

### ISSUE THREAD

**Issue by suntong** [knq/xo#37]
I know most often we should put all tables in the same DB, but I do have a case to deal with different DBs in the same project, because the content in each DB is totally irrelevant to other DBs. 

How to deal with Multi-DBs in the same project? Can they co-exist in the same `models` folder? Or, I have to use `-o ` to generate them into different model folders? The latter is something I want to avoid. Thx.

**Comment by kenshaw** [comment]
Yes, you can use xo to generate models for two different databases, and have them coexist in the same Go package. You would need to run xo twice, pointing at the two different databases. Please note that I have no intention of ever changing xo to process multiple databases at the same time.
