### ISSUE TITLE
Fails to generate <table>ByID methods for some tables

### ISSUE THREAD

**Issue by mccolljr** [knq/xo#4]
Let me start by saying that I'm thrilled with the work being done on this utility.
I see XO as being an integral part of bootstrapping web applications written in GO,
and I'd love to see how it continues to grow.
Unfortunately I'm having a problem.
I've got a schema for MySQL 5.5.46 (which I've attached),
which had fallen victim to Issue #3 
I went through and removed indexes until XO was able to run completely.
The generated code had a couple issues.
First, some of the (table)ByID methods were defined like this:

    func ArtistByID(db XODB, iD int64, iD int64, iD int, iD int64, iD int64, iD int64, iD int64, iD int64)(*Artist, error) {...}

There were also a couple of tables which didn't have a (table)ByID method generated.

I haven't really dug into this, I will when I have a chance tomorrow.
[db_init.txt](https://github.com/knq/xo/files/147511/db_init.txt)

**Comment by kenshaw** [comment]
Glad you like it. This is a known error, I just woke up and am literally fixing the issue, hopefully "once and for all" for both PostgreSQL and MySQL. I've been working on the last 4 days on this, it's a very massive overhaul as I had to rethink the way things were being generated from the database, consolidating code, etc. I'm hoping it'll be fixed today or, at the latest, tomorrow. Please watch for pushes and try with your specific schema when its done.

**Comment by mccolljr** [comment]
Thank you,

I was unsure if this was related to #3.

Much appreciated.

**Comment by kenshaw** [comment]
One note -- I noticed these are not InnoDB tables. xo will likely never work with non-relational tables in MySQL, as they don't define all the proper constraints/definitions for the schema properly. I'll create a DB with your schema on my end and see if that is an issue.

If that is indeed the problem, then the fix is to migrate your tables to InnoDB and/or migrate to postgres ;)

**Comment by kenshaw** [comment]
Somewhat good news: so I'm pretty sure the reason the old code didn't work was because your tables are not InnoDB tables. That said, the new version should work with both non MyISAM and InnoDB tables, as I've changed the way index information is being retrieved from the database. Hopefully, it should be done today.

**Comment by mccolljr** [comment]
I converted my schema for postgres, and that gave me consistent results as well.
I don't normally work with postgres but this is a nice motivation to start.
Thanks for your work on this.

**Comment by kenshaw** [comment]
I pushed out the latest revision. Please test and let me know how it works.

**Comment by mccolljr** [comment]
I was able to successfully convert my original schema to Go code, so success there!
I noticed that there does not appear to be support for nullable types. This isn't a huge deal, but is this the intention, and if so do you plan to add it in the future?

**Comment by kenshaw** [comment]
Huh? Nullable columns work just fine. Is there a specific place that a struct should have a sql.Null definition that it isn't getting now?

**Comment by mccolljr** [comment]
create table locale (
     ID bigint not null auto_increment primary key,
     parent bigint,
     charcode varchar(10) not null,
     name varchar(50) not null,
     latitude float,
     longitude float,
     class enum('city', 'state', 'country') not null,
     #constraint parent_locale unique(parent, name),
     foreign key (parent) references locale(ID) on delete set null
    ) ENGINE = InnoDB;

This is the table definition, this is the generated code:
    type Locale struct {
    	ID        int64   // ID
    	Parent    int64   // parent
    	Charcode  string  // charcode
    	Name      string  // name
    	Latitude  float32 // latitude
    	Longitude float32 // longitude
    	Class     Class   // class
    
    	// xo fields
    	_exists, _deleted bool
    }

Parent, Latitude and Longitude are the fields I expected to have nullably types.

**Comment by kenshaw** [comment]
On Sat, Feb 27, 2016 at 5:34 AM, Jacob R. McCollum <notifications@github.com
> wrote:

> create table locale (
>  ID bigint not null auto_increment primary key,
>  parent bigint,
>  charcode varchar(10) not null,
>  name varchar(50) not null,
>  latitude float,
>  longitude float,
>  class enum('city', 'state', 'country') not null,
>  #constraint parent_locale unique(parent, name),
>  foreign key (parent) references locale(ID) on delete set null
> ) ENGINE = InnoDB;
>
>
Ok -- I see the problem. The MySQL inspection query for that is treating
is_nullable as a boolean, when it is a string. I'll push a fix out for this
within the hour.

-Ken

**Comment by mccolljr** [comment]
Thanks for the quick work, much appreciated.

**Comment by kenshaw** [comment]
I just pushed a fix out for this. I appreciate you using / testing your schemas against it, as I don't really use MySQL much. A generic tool like this can only be good if others are also using it / providing feedback on problem(s) they've encountered.

**Comment by mccolljr** [comment]
Beautiful, this worked like a charm.
I'm happy to use it, it's been a huge time saver already and I'm sure it will continue to be as the project I'm working on progresses and the database needs continual migration.
