### ISSUE TITLE
--custom-types-package not imported.

### ISSUE THREAD

**Issue by pavelz** [knq/xo#47]
I suppose it would be nice to add -  --custom-types-package-import-line.

For example I have been generating models from my rails app and there is an Inet Type. --custom-types-package property subbed unimplemented types but failed to import the package. I can deal with unsupported types by adding a file to models directory with package 'models' which will cover unsupported types and it seems a little bit more elegant in lieu of import("appname/xocustom") ...

**Comment by kenshaw** [comment]
You probably need to do `go install <package>` for it to work properly with `goimports` which is what xo uses to resolve packages.

If you'd like to submit a pull request for adding a separate option, I would definitely consider it for inclusion!
