### ISSUE TITLE
not sure what to do next error in mysql.type.go.tpl

### ISSUE THREAD

**Issue by willie** [knq/xo#5]
Running xo with mysql:// and I got the following error (this is the entire error):

`error: template: mysql.type.go.tpl:1: illegal number syntax: "-"`

I'm not familiar with Go templates, so I'm at a loss for debugging. Any suggestions? 

(BTW, I'm super pumped for this project. It looks like exactly what I want.)

**Comment by willie** [comment]
I did have one thought: I'm running Go 1.5 on the box where I am trying to run this.

**Comment by kenshaw** [comment]
This is because of the new template trim syntax that was introduced in Go 1.6. There are no plans to change the templates to work with older Go versions. If you need to stick with using Go 1.5, I would suggest compiling xo with Go 1.6 for now. The code generated by xo should work with Go 1.3+.

**Comment by willie** [comment]
Thanks for the quick answer. Much appreciated.
