### ISSUE TITLE
Broken code emited for table called time

### ISSUE THREAD

**Issue by nefthy** [knq/xo#56]
Whene a table is called time, a type Time is created and all timerelated columns are mapped to it. For example. For example:

```sql
 CREATE TABLE `times` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `start` time DEFAULT NULL,
  `end` time DEFAULT NULL,
  `project` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `txt` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=648 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

produces:
```go
type Time struct {
	ID      int            `json:"id"`      // id
	Date    *time.Time `json:"date"`    // date
	Start   Time           `json:"start"`   // start
	End     Time           `json:"end"`     // end
	Project sql.NullString `json:"project"` // project
	Txt     sql.NullString `json:"txt"`     // txt

	// xo fields
	_exists, _deleted bool
}
```

Start and End should be *mysql.NullTime or *time.Time in case of NOT NULL.

**Comment by kenshaw** [comment]
I've added "time" to the mysql recognized types. Please test this and let me know if that works as expected.

**Comment by DevXeni** [comment]
Hi,
I'v got this error:
sql: Scan error on column index 3: unsupported Scan, storing driver.Value type []uint8 into type *time.Time

table struct

// CatalogCategoryEntity represents a row from 'catalog_category_entity'.
type CatalogCategoryEntity struct {
	EntityID       uint           `json:"entity_id"`        // entity_id
	AttributeSetID int16          `json:"attribute_set_id"` // attribute_set_id
	ParentID       uint           `json:"parent_id"`        // parent_id
	CreatedAt      *time.Time     `json:"created_at"`       // created_at
	UpdatedAt      *time.Time     `json:"updated_at"`       // updated_at
	Path           string         `json:"path"`             // path
	Position       int            `json:"position"`         // position
	Level          int            `json:"level"`            // level
	ChildrenCount  int            `json:"children_count"`   // children_count
	GUID           sql.NullString `json:"guid"`             // guid
	ParentGUID     sql.NullString `json:"parent_guid"`      // parent_guid

	// xo fields
	_exists, _deleted bool
}
