### ISSUE TITLE
Binary release for Microsoft SQL Server

### ISSUE THREAD

**Issue by suntong** [knq/xo#62]
Hi, 

I know Microsoft SQL Server are now supported in Linux, but I need the `xo` executable under Microsoft Windows. Can you build a `xo` binary release for Microsoft Windows please?

I tried it myself but found it is too much a mouthful for me:

```
...\Go\src\github.com\knq\xo>go build -v
github.com/alexflint/go-arg
github.com/knq/dburl
github.com/gedex/inflector
github.com/knq/snaker
github.com/knq/xo/models
github.com/knq/xo/templates
golang.org/x/net/context
github.com/go-sql-driver/mysql
github.com/denisenkom/go-mssqldb
github.com/lib/pq/oid
github.com/lib/pq
github.com/knq/xo/internal
github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
```

Have you ever built a `xo` executable under Microsoft Windows? If doing a binary release is too much a hassle, can you put the executable somewhere that I can grab please? Thanks!

**Comment by suntong** [comment]
Or, is it true that Microsoft SQL Server has always been under Linux? I.e., the `mssql` from [Initial Microsoft SQL Server support](https://github.com/knq/xo/commit/c4aa40ae226f8611a9a1d4c99bdf05970e044fc4) has been a Linux command from day one?

**Comment by suntong** [comment]
`xo` executable under Linux can access Microsoft SQL Server under Microsoft Windows just fine.

**Comment by turnkey-commerce** [comment]
Hi suntong,  I didn't have any trouble building the xo binary under Windows, but it's true you need to have gcc in the path.   I get gcc from the MinGW for Windows:

http://www.mingw.org/

That will show up for any Go executable that includes a package like the sqlite3 that has c libraries included.

**Comment by suntong** [comment]
Thanks! Good to know.
