### ISSUE TITLE
Generate functions twice

### ISSUE THREAD

**Issue by IAD** [knq/xo#66]
Steps to reproduce: 
- use MySQL database
- create 2 indexes for the same column
- generate models

```
// ActivityByActivityID returns the Activity associated with the ActivityReport's ActivityID (activity_id).
//
// Generated from foreign key 'activity_reports_ibfk_1'.
func (ar *ActivityReport) ActivityByActivityID(db XODB) (*Activity, error) {
	return ActivityByID(db, ar.ActivityID)
}

// ActivityByActivityID returns the Activity associated with the ActivityReport's ActivityID (activity_id).
//
// Generated from foreign key 'fk_ar_activity'.
func (ar *ActivityReport) ActivityByActivityID(db XODB) (*Activity, error) {
	return ActivityByID(db, ar.ActivityID)
}

```

**Comment by kenshaw** [comment]
xo has the options `--fk-mode` and `--use-index-names` that provide for a way to alter the generated func names for foreign keys / index queries. Unfortunately, there are limits that xo can do to predict name changes. Using `--fk-mode=key` should instead generate func's that named ActivityByReportsIbfk1 and ActivityByFkArActivity for those two foreign keys.
