### ISSUE TITLE
MySQL. Missed package name for the type "Time" 

### ISSUE THREAD

**Issue by IAD** [knq/xo#67]
Probably(not sure) if an attribute name ends with "Time" - package name is missed
see the "PaymentTime" attribute

```
CREATE TABLE `event_purchase` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `payment_date` date NOT NULL,
  `payment_time` time DEFAULT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=latin1

```

```
	PaymentDate     *time.Time     `json:"payment_date"`     // payment_date
	PaymentTime     Time           `json:"payment_time"`     // payment_time
```

**Comment by kenshaw** [comment]
MySQL supports a lot of aliases for other types, and unfortunately xo doesn't try to cover all of them at this time. I would just simply suggest changing your schema to use timestamps if possible. Also, I'm more than willing to take a pull request with the added name alias for the Go type.
