### ISSUE TITLE
Support for views 

### ISSUE THREAD

**Issue by tlianza** [knq/xo#72]
I'd really like to have support for views in Postgres. I can take a stab at building this if you have a sense for what structure you'd like to see it take. I see signs that it's already been considered via the view reltype, so I'm guessing there's some sense at how you'd like to see it look? A "ViewList" next to the "TableList" in the SchemaLoader?

**Comment by kenshaw** [comment]
Sorry I missed this before. Most of the SQL loaders for xo today (I think all of them?) would see a view the same as a table. As such, a type would be created for it in the same way as it would be for a regular table.

**Comment by mccolljr** [comment]
I'm bumping this because I've just run XO on a database of mine that has views, and a type was not created for my view.

It's entirely possible there's something missing in my schema which would prevent xo from recognizing this view, but I'm not sure what that would be.

**Comment by kenshaw** [comment]
What database are you working with? I'd really need to know more about the schema you're using.

**Comment by mccolljr** [comment]
```sh
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64)
```

Schema
```sql
-- Create syntax for TABLE 'accounts'
CREATE TABLE `accounts` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `unique_name` varchar(100) NOT NULL DEFAULT '',
  `pwhash` text NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_name` (`unique_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for VIEW 'userInfo'
CREATE VIEW `userInfo`
AS SELECT
   `users`.`firstname` AS `firstName`,
   `users`.`lastname` AS `lastName`,
   `acct`.`unique_name` AS `userName`,
   `acct`.`id` AS `accountID`,
   `users`.`id` AS `userID`,
   `acct`.`active` AS `active`
FROM (`users` join `accounts` `acct` on((`users`.`account` = `acct`.`id`)));

-- Create syntax for TABLE 'users'
CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `firstname` varchar(40) NOT NULL DEFAULT '',
  `lastname` varchar(40) NOT NULL DEFAULT '',
  `account` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `account` (`account`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`account`) REFERENCES `accounts` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by mccolljr** [comment]
When I run XO on this database, I'm getting types for User and Account, but not for UserInfo.
Originally I was generating queries for my custom type of UserInfo, using the xo's query mode, but I decided to switch to a view for simplicity's sake.

This is just a test schema from me playing around with MySQL trying to get more familiar with the more advanced syntax, so I'm sure there's something I've not done which would prevent XO from detecting my view.

**Comment by kenshaw** [comment]
Not sure at the moment. If you run `xo` with the `-v` flag, you can see the actual SQL queries being sent to the database. You can try those directly using the `mssql` cli tool, and see if `xo` is picking up the view as needed. I'll take a look into this, but I'm really backlogged at the moment, so not likely to get to this for the next couple of days.

**Comment by mccolljr** [comment]
Sorry, should have done that off the bat.

The following query appears to be the culprit:

```
SQL:
SELECT table_name FROM information_schema.tables WHERE table_schema = ? AND table_type = ?
PARAMS:
[deed BASE TABLE]
```

The MySQL loader appears not to be looking up for `table_type=VIEW`, only `BASE_TABLE`

Would the solution here simply be to add an or condition to that query, or would more be required?
I haven't looked at xo's source in some time.

**Comment by mccolljr** [comment]
It turns out that support for views wasn't enabled, in that there was never a quert to pull tables with a table_type of view.

I submit a very small pull request that fixes this issue:

#91
