### ISSUE TITLE
Support for postgres interval field doesn't seem to work

### ISSUE THREAD

**Issue by tlianza** [knq/xo#73]
postgres.go has this mapping:

```
case "interval":
    typ = "*time.Duration"
```
But, I get this error during a query:

> panic: Error fetching row in database: sql: Scan error on column index 17: converting driver.Value type []uint8 ("00:01:02.399998") to a int64: invalid syntax

And, it seems like there isn't actually support for this mapping in the pg library:
https://github.com/lib/pq/issues/78

**Comment by kenshaw** [comment]
Oh. Interesting. For the record I did not test this type, as "intervals" are not really used directly in schemas much, as a "postgres interval" can't really have the same meaning as a "php interval" (for example). Only by coincidence would two "interval" definitions match, or if one basically followed the interval implementation. That said, I don't feel this is necessary to change this as I don't believe a critical number of users would be using intervals in their schema (the work around is to not use them), and second, if anything the proper implementation for "interval" by Go's definition would, indeed, be time.Duration.
