### ISSUE TITLE
error: too many open files

### ISSUE THREAD

**Issue by crimsonblue02** [knq/xo#78]
Ran xo from terminal...
$xo mssql://user:password@host:port/dbname -o models

... and received the following error
error: open models/tablename.xo.go: too many open files

The Sql Server db I'm trying to use has at least 100 tables. Is there a way to digest in chunks?

**Comment by kenshaw** [comment]
Increase your operating system's max open file limits. It must be set extremely low if this error is happening and there's only a hundred tables in your schema.

**Comment by crimsonblue02** [comment]
Thanks!

For anyone on OSX this blog post solved this -> [https://blog.dekstroza.io/ulimit-shenanigans-on-osx-el-capitan/]
