### ISSUE TITLE
error: pq: SSL is not enabled on the server

### ISSUE THREAD

**Issue by hudarui** [knq/xo#79]

**Comment by turnkey-commerce** [comment]
It looks like you need to pass an option to indicate this on your connection string.

http://stackoverflow.com/questions/21959148/ssl-is-not-enabled-on-the-server

**Comment by hudarui** [comment]
thanks. I understand

**Comment by turnkey-commerce** [comment]
No problem.

**Comment by kenshaw** [comment]
You need to pass the ?sslmode= option to the URL.
