### ISSUE TITLE
errors when a column name matches a go reserved keyword

### ISSUE THREAD

**Issue by willie** [knq/xo#8]
If your database table has a field named "type" or some other go reserved keyword and it's part of some index, then xo will name some local variables "type" which collides with the reserved keyword.

Some examples:

```
// ProductsByParentIDType retrieves a row from 'phx.products' as a Product.
//
// Generated from index 'products_parent_id_type'.
func ProductsByParentIDType(db XODB, parentID sql.NullInt64, type sql.NullString) ([]*Product, error) {
```

```
// ProductsBySkuIDType retrieves a row from 'phx.products' as a Product.
//
// Generated from index 'ku_id_type'.
func ProductsBySkuIDType(db XODB, sku sql.NullString, id int, type sql.NullString) ([]*Product, error) {
```

Renaming the variable from "type" to some other name ("t", for example) solves the problem.

**Comment by kenshaw** [comment]
This is easy to fix. There's a goparamlist func in internal/funcs.go that implements this. I will add a check for Go reserved names and create a map so that if there are collisions, then it doesn't produce a build error.

**Comment by kenshaw** [comment]
Just pushed a fix for this.

**Comment by willie** [comment]
Confirmed.

**Comment by Xeoncross** [comment]
This is still an issue. I have a field named "error" on one of my tables which produces the following invalid go code.

```
url {
    url text,
    error int
}
```

```
// URLsByError retrieves a row from 'dbnamehere.url' as a URL.
//
// Generated from index 'url_error_index'.
func URLsByError(db XODB, error sql.NullInt64) ([]*URL, error) {
	var err error

```

**Comment by Xeoncross** [comment]
@kenshaw wins an award for responding in 9 seconds at 9pm Saturday night.

**Comment by kenshaw** [comment]
It's Sunday morning for me, and I was right in the middle of coding something else related to xo. I just pushed a change. Please try it out and let me know if that fixes the error issue.

**Comment by Xeoncross** [comment]
Close, but you might want to pick a name your not using like "errorString" or something.

```
func URLsByError(db XODB, err sql.NullInt64) ([]*URL, error) {
	var err error
```

**Comment by kenshaw** [comment]
So picky. (kidding)

**Comment by kenshaw** [comment]
I'm adding all built in type names now.

**Comment by kenshaw** [comment]
Ok, please try again.

**Comment by Xeoncross** [comment]
Works great!
