### ISSUE TITLE
dsn password contains #,parse error

### ISSUE THREAD

**Issue by unei66** [knq/xo#80]
Hi:
    I used xo like this:

   ```
    ~$ xo mysql://root:123#4567@localhost/test -s user_info -o models       
    error: invalid DSN: missing the slash separating the database name   
   ```

   password contains #,so the dsn parse error.
   because of xo used the net.url parse dsn or my usage has problems?

**Comment by kenshaw** [comment]
Try this: xo 'mysql://root:123%234567@localhost/test'
