### ISSUE TITLE
Column escaping uses the wrong quote character for MySQL

### ISSUE THREAD

**Issue by jjsil** [knq/xo#90]
The default identifier [quote character for MySQL is the backtick](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html) (`) 
instead of the double quote (") used in [Postgres](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html).

This means that columns in WHERE clauses are interpreted as strings instead of column references.

When generating code using --escape-column and targeting MySQL, queries like these are sent to MySQL after replacing parameters:
`SELECT "UserId", "Username" FROM Users WHERE "Username" = "jjso"`
This query always returns 0 results because it's comparing two string constants instead of the column value with the string.

**Comment by kenshaw** [comment]
Hi thanks -- please see my comments on the PR.

**Comment by jjsil** [comment]
A quick followup on this: setting sql_mode=ANSI has plenty of side effects because it doesn't just change the quotes. In our case it disabled strict mode, which enabled truncation and could have resulted in data loss if we hadn't caught it early.

In the end we've had to change the SQL_MODE on the server, which ended up affecting other binaries written in other languages. Luckily they dealt with the change gracefully but it could have been a nightmare of changes and we probably would have ended up with us switching away from xo.

Might be worth revisiting making the escaping character something that can be configured.
