### ISSUE TITLE
xo cannot execute macOS 10.12.4 / Xcode 8.3

### ISSUE THREAD

**Issue by miiton** [knq/xo#92]
I cannot execute xo command after update xcode to 8.3.

This problem has been reported in golang/go#19734

![1 tmux 2017-03-29 20-16-51](https://cloud.githubusercontent.com/assets/468745/24452195/0ac7dd86-14bd-11e7-980f-770a4a7ee4f9.png)

**Comment by kenshaw** [comment]
Appreciate the report; I don't think this is a problem with `xo` though -- it looks like this is going to be fixed with `go1.8.1`. Maybe try with Go's `tip` branch?

**Comment by miiton** [comment]
Yes, I think so too.
However, since it seems that Go does not yet have a commit to this problem, I have reported so that users of xo will not get confused.

**Comment by kenshaw** [comment]
Thanks, appreciate the heads up!
