### ISSUE TITLE
Latest simply will not run on Mac 10.12.1 (Killed: 9)

### ISSUE THREAD

**Issue by robmuh** [knq/xo#95]
This was working fine about two months ago and after an update to both go and xo seems this software combination no longer functions, which is a huge show-stopper for us. Dropping. Can't afford this level of uncertainty. Will roll our own instead. Love the idea though.

**Comment by kenshaw** [comment]
This is a known problem with Go -- https://github.com/golang/go/issues/19734 --  that I believe was fixed in Go 1.8.1 (but I haven't checked). You need to compile it like the following:

```go
go build -ldflags='-w -s'
```

**Comment by robmuh** [comment]
Thank you that did the trick. Sorry for the dramatic report. I really have
a core dependency on `xo` and was always really leery of putting that big a
dependency into my architecture.

*Rob Muhlestein*
@SkilStak <http://twitter.com/skilstak>, Inc.
rob@skilstak.com
704-310-6778
@robmuh <http://twitter.com/robmuh>
