### ISSUE TITLE
Doesn't generate all methods for same named non-unique index name across multiple tables 

### ISSUE THREAD

**Issue by ammario** [knq/xo#97]
I have an index for `owner` on table `users` and index `owner` on table `applications`.

XO never generates both `UsersByOwner` and `ApplicationsByOwner` functions, it generates one or the other at random.

It doesn't seem to be broken for primary/unique index types.

A makeshift solution is to rename the `owner` index to `<tablename>_owner` but that's not ideal.

Thanks.

**Comment by kenshaw** [comment]
If this is generating at "random" this is probably some manifestation of a Go map key order problem, and its getting overwritten at random.

Could you share more information about what database you are using, and the actual schema? It would be great if you could provide a reduced schema that consistently recreates this problem. For the record, `xo` does not have great support for multi-key indexes / primary keys.

**Comment by ammario** [comment]
I was able to replicate with the following schema

```sql
SET NAMES utf8;
SET time_zone = '+00:00';

CREATE TABLE `apps` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

I'm using MySQL 5.7.17

I've investigated further with the verbose flag set. It appears latency is the deciding factor.

The last index information query to return is for the table with properly generated methods.
